CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

CREATE TABLE "TodoItems" (
                             "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
                             "Name" text NULL,
                             "IsComplete" boolean NOT NULL,
                             CONSTRAINT "PK_TodoItems" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211122170126_InitialCreate', '6.0.0');

COMMIT;
